name: locami
description: map record app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.1
  geolocator: ^14.0.2
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.3
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  permission_handler: ^12.0.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.0
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
